server:
  port: 8081
spring:
  application:
    name: todo-management
springdoc:
  swagger-ui:
    enabled: true
    path: v1/swagger-ui.html
  api-docs:
    path: v1/docs
logging:
  level:
    org.springdoc: DEBUG
